config/routes.rb
Rails.application.routes.draw do
  resources :projects_performances
  resources :projects_managers
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/projects_manager.rb
class ProjectsManager < ApplicationRecord
    # after_save :initialize_project_performance

    # def initialize_project_performance
    #     # ProjectsPerformance.create!(project_manager_id: self.id, expected_days: self.end_date - self.start_date, phase_status: "Inicio" )
    #     ProjectsPerformance.new
    # end
    
end

app/models/projects_performance.rb
class ProjectsPerformance < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/projects_managers_controller.rb
class ProjectsManagersController < ApplicationController
  before_action :set_projects_manager, only: [:show, :edit, :update, :destroy]

  # GET /projects_managers
  # GET /projects_managers.json
  def index
    @projects_managers = ProjectsManager.all
  end

  # GET /projects_managers/1
  # GET /projects_managers/1.json
  def show
  end

  # GET /projects_managers/new
  def new
    @projects_manager = ProjectsManager.new
  end

  # GET /projects_managers/1/edit
  def edit
  end

  # POST /projects_managers
  # POST /projects_managers.json
  def create
    @projects_manager = ProjectsManager.new(projects_manager_params)

    respond_to do |format|
      if @projects_manager.save
        format.html { redirect_to @projects_manager, notice: 'Projects manager was successfully created.' }
        format.json { render :show, status: :created, location: @projects_manager }
      else
        format.html { render :new }
        format.json { render json: @projects_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_managers/1
  # PATCH/PUT /projects_managers/1.json
  def update
    respond_to do |format|
      if @projects_manager.update(projects_manager_params)
        format.html { redirect_to @projects_manager, notice: 'Projects manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_manager }
      else
        format.html { render :edit }
        format.json { render json: @projects_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_managers/1
  # DELETE /projects_managers/1.json
  def destroy
    @projects_manager.destroy
    respond_to do |format|
      format.html { redirect_to projects_managers_url, notice: 'Projects manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_manager
      @projects_manager = ProjectsManager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projects_manager_params
      params.require(:projects_manager).permit(:start_date, :end_date, :number_of_changes, :service_type, :project_value, :manager, :allocated_members, :nps_rate, :observations)
    end
end

app/controllers/projects_performances_controller.rb
class ProjectsPerformancesController < ApplicationController
  before_action :set_projects_performance, only: [:show, :edit, :update, :destroy]

  # GET /projects_performances
  # GET /projects_performances.json
  def index
    @projects_performances = ProjectsPerformance.all
  end

  # GET /projects_performances/1
  # GET /projects_performances/1.json
  def show
  end

  # GET /projects_performances/new
  def new
    @projects_performance = ProjectsPerformance.new
  end

  # GET /projects_performances/1/edit
  def edit
  end

  # POST /projects_performances
  # POST /projects_performances.json
  def create
    @projects_performance = ProjectsPerformance.new(projects_performance_params)

    respond_to do |format|
      if @projects_performance.save
        format.html { redirect_to @projects_performance, notice: 'Projects performance was successfully created.' }
        format.json { render :show, status: :created, location: @projects_performance }
      else
        format.html { render :new }
        format.json { render json: @projects_performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_performances/1
  # PATCH/PUT /projects_performances/1.json
  def update
    respond_to do |format|
      if @projects_performance.update(projects_performance_params)
        format.html { redirect_to @projects_performance, notice: 'Projects performance was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_performance }
      else
        format.html { render :edit }
        format.json { render json: @projects_performance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_performances/1
  # DELETE /projects_performances/1.json
  def destroy
    @projects_performance.destroy
    respond_to do |format|
      format.html { redirect_to projects_performances_url, notice: 'Projects performance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_performance
      @projects_performance = ProjectsPerformance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def projects_performance_params
      params.require(:projects_performance).permit(:expected_days, :running_days, :phase_status, :number_of_sprints, :accomplished)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_managers_helper.rb
module ProjectsManagersHelper
end

app/helpers/projects_performances_helper.rb
module ProjectsPerformancesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects_managers/_form.html.erb
<%= form_with(model: projects_manager, local: true) do |form| %>
  <% if projects_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_manager.errors.count, "error") %> prohibited this projects_manager from being saved:</h2>

      <ul>
        <% projects_manager.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :number_of_changes %>
    <%= form.number_field :number_of_changes %>
  </div>

  <div class="field">
    <%= form.label :service_type %>
    <%= form.text_field :service_type %>
  </div>

  <div class="field">
    <%= form.label :project_value %>
    <%= form.text_field :project_value %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.text_field :manager %>
  </div>

  <div class="field">
    <%= form.label :allocated_members %>
    <%= form.text_field :allocated_members %>
  </div>

  <div class="field">
    <%= form.label :nps_rate %>
    <%= form.number_field :nps_rate %>
  </div>

  <div class="field">
    <%= form.label :observations %>
    <%= form.text_area :observations %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects_managers/edit.html.erb
<h1>Editing Projects Manager</h1>

<%= render 'form', projects_manager: @projects_manager %>

<%= link_to 'Show', @projects_manager %> |
<%= link_to 'Back', projects_managers_path %>

app/views/projects_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects Managers</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Number of changes</th>
      <th>Service type</th>
      <th>Project value</th>
      <th>Manager</th>
      <th>Allocated members</th>
      <th>Nps rate</th>
      <th>Observations</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects_managers.each do |projects_manager| %>
      <tr>
        <td><%= projects_manager.start_date %></td>
        <td><%= projects_manager.end_date %></td>
        <td><%= projects_manager.number_of_changes %></td>
        <td><%= projects_manager.service_type %></td>
        <td><%= projects_manager.project_value %></td>
        <td><%= projects_manager.manager %></td>
        <td><%= projects_manager.allocated_members %></td>
        <td><%= projects_manager.nps_rate %></td>
        <td><%= projects_manager.observations %></td>
        <td><%= link_to 'Show', projects_manager %></td>
        <td><%= link_to 'Edit', edit_projects_manager_path(projects_manager) %></td>
        <td><%= link_to 'Destroy', projects_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projects Manager', new_projects_manager_path %>

app/views/projects_managers/new.html.erb
<h1>New Projects Manager</h1>

<%= render 'form', projects_manager: @projects_manager %>

<%= link_to 'Back', projects_managers_path %>

app/views/projects_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @projects_manager.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @projects_manager.end_date %>
</p>

<p>
  <strong>Number of changes:</strong>
  <%= @projects_manager.number_of_changes %>
</p>

<p>
  <strong>Service type:</strong>
  <%= @projects_manager.service_type %>
</p>

<p>
  <strong>Project value:</strong>
  <%= @projects_manager.project_value %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @projects_manager.manager %>
</p>

<p>
  <strong>Allocated members:</strong>
  <%= @projects_manager.allocated_members %>
</p>

<p>
  <strong>Nps rate:</strong>
  <%= @projects_manager.nps_rate %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @projects_manager.observations %>
</p>

<%= link_to 'Edit', edit_projects_manager_path(@projects_manager) %> |
<%= link_to 'Back', projects_managers_path %>

app/views/projects_performances/_form.html.erb
<%= form_with(model: projects_performance, local: true) do |form| %>
  <% if projects_performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_performance.errors.count, "error") %> prohibited this projects_performance from being saved:</h2>

      <ul>
        <% projects_performance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :expected_days %>
    <%= form.number_field :expected_days %>
  </div>

  <div class="field">
    <%= form.label :running_days %>
    <%= form.number_field :running_days %>
  </div>

  <div class="field">
    <%= form.label :phase_status %>
    <%= form.text_field :phase_status %>
  </div>

  <div class="field">
    <%= form.label :number_of_sprints %>
    <%= form.number_field :number_of_sprints %>
  </div>

  <div class="field">
    <%= form.label :accomplished %>
    <%= form.number_field :accomplished %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects_performances/edit.html.erb
<h1>Editing Projects Performance</h1>

<%= render 'form', projects_performance: @projects_performance %>

<%= link_to 'Show', @projects_performance %> |
<%= link_to 'Back', projects_performances_path %>

app/views/projects_performances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects Performances</h1>

<table>
  <thead>
    <tr>
      <th>Expected days</th>
      <th>Running days</th>
      <th>Phase status</th>
      <th>Number of sprints</th>
      <th>Accomplished</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects_performances.each do |projects_performance| %>
      <tr>
        <td><%= projects_performance.expected_days %></td>
        <td><%= projects_performance.running_days %></td>
        <td><%= projects_performance.phase_status %></td>
        <td><%= projects_performance.number_of_sprints %></td>
        <td><%= projects_performance.accomplished %></td>
        <td><%= link_to 'Show', projects_performance %></td>
        <td><%= link_to 'Edit', edit_projects_performance_path(projects_performance) %></td>
        <td><%= link_to 'Destroy', projects_performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projects Performance', new_projects_performance_path %>

app/views/projects_performances/new.html.erb
<h1>New Projects Performance</h1>

<%= render 'form', projects_performance: @projects_performance %>

<%= link_to 'Back', projects_performances_path %>

app/views/projects_performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expected days:</strong>
  <%= @projects_performance.expected_days %>
</p>

<p>
  <strong>Running days:</strong>
  <%= @projects_performance.running_days %>
</p>

<p>
  <strong>Phase status:</strong>
  <%= @projects_performance.phase_status %>
</p>

<p>
  <strong>Number of sprints:</strong>
  <%= @projects_performance.number_of_sprints %>
</p>

<p>
  <strong>Accomplished:</strong>
  <%= @projects_performance.accomplished %>
</p>

<%= link_to 'Edit', edit_projects_performance_path(@projects_performance) %> |
<%= link_to 'Back', projects_performances_path %>